services:
  mira-fe:
    container_name: mira-fe
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api-creator.mira-studio.ai}
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: ${PORT:-8001}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api-creator.mira-studio.ai}
    ports:
      - "${PORT:-8001}:8001"
    restart: unless-stopped
